config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations'}
  get 'home/index'
  root 'home#index'
  resources :messages do
    collection do
      get :send_index
      get :notify
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  validates :title, presence: true
  
  scope :not_read, -> {where(is_read: false)}

  belongs_to :receiver, class_name: 'User'
  belongs_to :sender, class_name: 'User'
end

app/models/user.rb
class User < ApplicationRecord

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :name, presence: true

  has_many :my_received_messages, class_name: 'Message', foreign_key: 'receiver_id'
  has_many :my_send_messages, class_name: 'Message', foreign_key: 'sender_id'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :authenticate_user!

  def index
    @messages = current_user.my_received_messages
    @messages.update(is_read: true)
  end

  def send_index
    @messages = current_user.my_send_messages
  end

  def notify
    count = current_user.my_received_messages.not_read.size
    render json: {count: count }
  end

  def new
    @receivers = User.where.not(id: current_user.id).pluck(:name, :id)
    @message = Message.new
  end

  def create
    @message = Message.new(message_params)
    @message.sender_id = current_user.id
    if @message.save
      redirect_to @message, notice: 'message sent success fully'
    else
      @receivers = User.where.not(id: current_user.id).pluck(:name, :id)
      render :new
    end
  end

  def show
    @message = Message.find(params[:id])
  end

  private
  def message_params
    params.require(:message).permit(:title, :content, :receiver_id)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private
  
  def sign_up_params 
    params.require(:user).permit(:name, :email, :password, :address, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:name, :email, :password, :address, :password_confirmation, :current_password)
  end

end 

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/home/index.html.erb
<div class="container-fluid">
  <h1 class="text-primary">Messenger</h1>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <ul class="navbar-nav">

      <li class="nav-item">
      <%= link_to 'Messanger', root_url, class: "navbar-brand" %>
      </li>
      <% if current_user %>
        <li class="nav-item">
          <%= link_to 'Send Message', new_message_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
        <%= link_to 'Message Outbox', send_index_messages_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
        <%= link_to messages_path, class: 'nav-link' do%>
          Message Inbox <span class="label label-primary" id="notify"></span>
        <% end %>
        <script>notify()</script>
        </li>
        <li class="nav-item">
          <div class = 'nav-link' >User: <%=current_user.name&.camelize%></div>
        </li>
        <li class="nav-item">
          <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: "nav-link"%>
        </li>
      <% else %>
        <li class="nav-item float-right">
          <%= link_to 'Sign in', user_session_path, class: "btn btn-outline-success my-2 my-sm-0"%>
          <%= link_to 'Sign up', new_user_registration_path, class: "btn btn-outline-success my-2 my-sm-0"%>
        </li>
      <% end %>
    </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Messenger</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <script>
    function notify()
    {
      $.ajax({
        url: "<%= notify_messages_path %>",
        type: 'GET',
        dataType: 'json',
        success: function(res) {
          console.log(res);
          $('#notify').html(res.count)
        }
      });
    }
  <% if current_user %>
    $(document).ready(function() {
      setInterval(function() {
      notify()
      }, 30000);
    });
    
  <% end %>
  </script>

  </head>
  <body>
    <%= render 'layouts/navbar.html.erb' %>
    <div class="container-fluid">
      <%= yield %>
    </div>
  </body>
</html>

app/views/messages/_form.html.erb
<%= form_with(model: message, local: true) do |form| %>
    <% if message.errors.any? %>
      <div id="error_explanation" class="error alert alert-danger">
        <h6><%= pluralize(message.errors.count, "error") %> prohibited this message from being saved:</h6>

        <ul>
        <% message.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group">
      <%= form.label :parent %>
      <%= form.select :receiver_id , options_for_select(@receivers),{ prompt: 'Select any one'}, { class: 'form-control' } %>
    </div>

    <div class="form-group">
      <%= form.label :title%>
      <%= form.text_field :title, :class => "form-control" %>
    </div>

    <div class="form-group">
      <%= form.label :content %>
      <%= form.text_area :content, :class => "form-control" %>
    </div>

    <div class="actions">
      <%= form.submit "Save", :class => "btn btn-info" %>
    </div>
  <% end %>

app/views/messages/_index.html.erb
<% @messages.each_with_index do |message, index| %>
  <tr>
  <td><%= index+1 %></td>
  <td><%= message.title %></td>
  <td><%= message.sender.name %></td>
  <td><%= message.created_at.strftime("%d/%m/%Y %I:%M%p") %></td>
  <td><%= link_to 'Show', message %></td>
  </tr>
<% end %>

app/views/messages/_send_index.html.erb
<% @messages.each_with_index do |message, index| %>
    <tr>
    <td><%= index+1 %></td>
    <td><%= message.title %></td>
    <td><%= message.receiver.name %></td>
    <td><%= message.created_at.strftime("%d/%m/%Y %I:%M%p") %></td>
    <td><%= link_to 'Show', message %></td>
    </tr>
  <% end %>

app/views/messages/index.html.erb
<div>Message Inbox</div>
<table class="table">
  <thead>
    <th>#</th>
    <th>Title</th>
    <th>Send by</th>
    <th>Send On</th>
    <th>Action</th>
  </thead>
  <tbody>
    <%= render 'index.html.erb' %>
  </tbody>
</div>

app/views/messages/new.html.erb
<div class="container">

	<h1>New Message</h1>

	<%= render 'form', message: @message %>
</div>

app/views/messages/send_index.html.erb
<div>Message Inbox</div>
<table class="table">
  <thead>
    <th>#</th>
    <th>Title</th>
    <th>Send To</th>
    <th>Send On</th>
    <th>Action</th>
  </thead>
  <tbody>
    <%= render 'send_index.html.erb' %>
  </tbody>
</div>

app/views/messages/show.html.erb
<div class="container" >
  <div class='row'>
    <div class="col-sm-2">Title</div>
    <div class="col-sm-10"><%= @message.title %></div>
  </div>
  <div class='row'>
    <div class="col-sm-2">Send By</div>
    <div class="col-sm-10"><%= @message.sender.name.camelize %></div>
  </div>
  <div class='row'>
    <div class="col-sm-2">Send To</div>
    <div class="col-sm-10"><%= @message.receiver.name.camelize %></div>
  </div>
  <div class='row'>
    <div class="col-sm-2">Send On</div>
    <div class="col-sm-10"><%= @message.created_at.strftime("%d/%m/%Y %I:%M%p") %></div>
  </div>
  <div class="row">
    <div class='col-sm-2'>Content</div>
    <div class="col-sm-10"><%= @message.content %></div>
  </div>
</div>